/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardWrapper: typeof import('./src/components/CardWrapper.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProgemntLogo: typeof import('./src/components/ProgemntLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheButton: typeof import('./src/components/TheButton.vue')['default']
  }
}
