version: "3"

services:
  php:
    build:
      context: "backend"
      dockerfile: "../.docker/php.dockerfile"
    volumes:
      - "./backend:/var/www/html/"
      - "./.docker/config:/etc/apache2/sites-available/"
    ports:
      - "8000:80"
